<?php

return [

    'active' =>[
        '0'=>'chưa xử lý',
        '1'=>'đã xác nhận',
        '2'=>'bỏ qua',

    ],

    'address' => [
        0=>'Lựa chọn',
        1=>'Hà nội',
        2=>'TP HCM',
        5=>'Hải Phòng',
        4=>'Đà Nẵng',
        6=>'An Giang',
        7=>'Bà Rịa-Vũng Tàu',
        13=>'Bình Dương',
        15=>'Bình Phước',
        16=>'Bình Thuận',
        14=>'Bình Định',
        8=>'Bạc Liêu',
        10=>'Bắc Giang',
        9=>'Bắc Kạn',
        11=>'Bắc Ninh',
        12=>'Bến Tre',
        18=>'Cao Bằng',
        17=>'Cà Mau',
        3=>'Cần Thơ',
        24=>'Gia Lai',
        25=>'Hà Giang',
        26=>'Hà Nam',
        27=>'Hà Tĩnh',
        30=>'Hòa Bình',
        28=>'Hải Dương',
        29=>'Hậu Giang',
        31=>'Hưng Yên',
        32=>'Khánh Hòa',
        33=>'Kiên Giang',
        34=>'Kon Tum',
        35=>'Lai Châu',
        38=>'Lào Cai',
        36=>'Lâm Đồng',
        37=>'Lạng Sơn',
        39=>'Long An',
        40=>'Nam Định',
        41=>'Nghệ An',
        42=>'Ninh Bình',
        43=>'Ninh Thuận',
        44=>'Phú Thọ',
        45=>'Phú Yên',
        46=>'Quảng Bình',
        47=>'Quảng Nam',
        48=>'Quảng Ngãi',
        49=>'Quảng Ninh',
        50=>'Quảng Trị',
        51=>'Sóc Trăng',
        52=>'Sơn La',
        53=>'Tây Ninh',
        56=>'Thanh Hóa',
        54=>'Thái Bình',
        55=>'Thái Nguyên',
        57=>'Thừa Thiên-Huế',
        58=>'Tiền Giang',
        59=>'Trà Vinh',
        60=>'Tuyên Quang',
        61=>'Vĩnh Long',
        62=>'Vĩnh Phúc',
        63=>'Yên Bái',
        19=>'Đắk Lắk',
        22=>'Đồng Nai',
        23=>'Đồng Tháp',
        21=>'Điện Biên',
        20=>'Đăk Nông',
    ]

];


